Entrega/LTAW/PRACTICA4/P4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Entrega/LTAW/PRACTICA4/shop/urls.py
from django.conf.urls import url

from . import views

app_name = 'shop'
urlpatterns = [
    # ex: /shop/
    url(r'^$', views.indexView, name='index'),
    # ex: /shop/search/..
    url(r'^search/$', views.search, name='search'),
    # ex: /shop/cart/
    url(r'^cart/(?P<item_id>\w+)/$', views.cartView, name='cart'),
    # ex: /shop/bikes/
    url(r'^(?P<genre_id>\w+)/$', views.genreView, name='genre'),
    # ex: /shop/bikes/results/
    url(r'^(?P<genre_id>\w+)/(?P<item_id>\w+)/$', views.itemView, name='item'),
]

Entrega/LTAW/PRACTICA4/shop/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.files.storage import FileSystemStorage

# Create your models here.
@python_2_unicode_compatible
class Genre(models.Model):
    id = models.CharField(primary_key=True, max_length= 200)
    text = models.CharField(max_length=200)
    imgsrc = models.ImageField(upload_to="media/shop/genre/Images", blank="True", default="static/shop/images/nodisp.jpg")
    audiosrc = models.FileField(upload_to="media/shop/genre/Audio", blank="True")
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.text

@python_2_unicode_compatible
class Item(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    id = models.CharField(primary_key=True, max_length= 200)
    text = models.CharField(max_length=200)
    price = models.IntegerField()
    inCart = models.BooleanField(default=False)
    imgsrc = models.ImageField(upload_to="media/shop/item/Images", blank="True", default="static/shop/images/nodisp.jpg")
    detailImgsrc = models.ImageField(upload_to="media/shop/item/detail/Images", blank="True")
    audiosrc = models.FileField(upload_to="media/shop/item/detail/Audio", blank="True")
    videosrc = models.FileField(upload_to="media/shop/item/detail/Video", blank="True")
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.text

@python_2_unicode_compatible
class Order(models.Model):
    orderId = models.CharField(max_length=200)
    orderPrice = models.IntegerField()
    ordererMail = models.CharField(max_length=200)
    ordererDir = models.CharField(max_length=200)

    def __str__(self):
        return self.ordererMail

Entrega/LTAW/PRACTICA4/shop/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from django.utils import timezone

from .models import Genre, Item, Order
from django.db.models import Sum

import re

from django.db.models import Q

# Create your views here.

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:

        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']

    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]


def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.

    '''
    query = None  # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None  # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

def indexView(request):
    genre_list = Genre.objects.order_by('pub_date')[:4]
    context = {'genre_list': genre_list}

    if (request.POST):
        mail = request.POST['mail']
        dir = request.POST['dir']
        id = mail + "," + dir

        item_list = Item.objects.filter(inCart = True)

        totalPrice = 0
        for item in item_list:
            totalPrice += item.price

        Order.objects.create(ordererMail = mail, ordererDir = dir, orderPrice = totalPrice, orderId = id)

        for item in item_list:
            item.inCart = False
            item.save()

    return render(request, 'shop/index.html', context)

def genreView(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    genre_list = Genre.objects.order_by('pub_date')[:4]
    item_list = Item.objects.filter(genre__id = genre_id).order_by('pub_date')[:4]
    context = {'genre_list': genre_list, 'item_list': item_list, 'actgenre': genre}
    return render(request, 'shop/genre.html', context)

def itemView(request, genre_id, item_id):
    # Echar un ojo a esto ya que deberia buscar genero y dentro del genero el item
    genre_list = Genre.objects.order_by('pub_date')[:4]
    item = get_object_or_404(Item, id=item_id)
    context = {'genre_list': genre_list, 'item': item}
    return render(request, 'shop/detail.html', context)

def cartView(request, item_id=None):
    if (item_id):
        addedItem = Item.objects.get(id = item_id)
        addedItem.inCart = not addedItem.inCart
        addedItem.save()

    genre_list = Genre.objects.order_by('pub_date')[:4]
    item_list = Item.objects.filter(inCart = True).order_by('pub_date')
    totalPrice = 0
    for item in item_list:
        totalPrice += item.price
    context = {'genre_list': genre_list, 'item_list': item_list, 'total': totalPrice}

    return render(request, 'shop/cart.html', context)

def search(request):
    genre_list = Genre.objects.order_by('pub_date')[:4]

    item_list = None

    if ('searchbox' in request.GET) and request.GET['searchbox'].strip():
        query_string = request.GET['searchbox']
        search_fields = ['text', 'id', 'genre__text', 'genre__id']

        entry_query = get_query(query_string, search_fields)

        item_list = Item.objects.filter(entry_query).order_by('pub_date')

    context = {'genre_list': genre_list, 'item_list': item_list}
    return render(request, 'shop/search.html', context)

Entrega/LTAW/PRACTICA4/shop/templates/shop/base.html
{% load staticfiles %}

<html lang="es">
	<head>
        <meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="{% static 'shop/shopStyle.css' %}">
        <title>Tienda Online</title>
	</head>
	<body>
		<div id="page">
			<header>
				<h1><a href="{% url 'shop:index' %}">Tiendachachiguachi.net</a></h1>
				<div id = "divmenu">
					<ul id="menu">
						{% for genre in genre_list %}
						<li><a href="{% url 'shop:genre' genre.id %}">{{ genre.text }}</a></li>
						{% endfor %}
					</ul>
				</div>
			</header>
			<aside>
				<form action="{% url 'shop:search' %}" method="get">
					<input id="searchbox" type="text" name="searchbox" placeholder="Search..."><br>
					<input type="submit" value="Search">
				</form>
				{% block aside %}
                {% endblock %}
			</aside>
                {% block optional %}
                {% endblock %}
			<section>
				{% block section %}
                {% endblock %}
			</section>
			<footer>
			</footer>
		</div>
	</body>
</html>

Entrega/LTAW/PRACTICA4/shop/templates/shop/cart.html
{% extends "shop/base.html" %}

{% load staticfiles %}

{% block aside %}
	<ul id="options">
		{% for genre in genre_list %}
		<li><a href="{% url 'shop:genre' genre.id %}"> {{ genre.text }} </a></li>
		{% endfor %}
	</ul>
{% endblock %}

{% block section %}
	<table>
		{% for item in item_list %}
		{% if not forloop.counter|divisibleby:2 %}
		<tr>
		{% endif %}
			<td>
				<div class="item">
					<a href = "{% url 'shop:item' 'detail' item.id %}">
						<img class="itemimg" src="{{item.imgsrc.url}}" alt="missing image">
					</a>
					<p> {{ item.text }} </p>
				</div>
			</td>
		{% if forloop.counter|divisibleby:2 %}
		</tr>
		{% endif %}
		{% endfor %}
	</table>
    <p><strong>Order ready!! Total price: {{total}}$</strong></p>
    <form action="{% url 'shop:index' %}" method="post">
	{% csrf_token %}
		<label>Mail:</label><input type="text" name="mail" placeholder="example@example.com"><br>
		<label>Dirección</label><input type="text" name="dir" placeholder="c/Falsa 123"><br>
        <input type="submit" value="Buy!">
	</form>
{% endblock %}

Entrega/LTAW/PRACTICA4/shop/templates/shop/detail.html
{% extends "shop/base.html" %}

{% load staticfiles %}

{% block aside %}
	<ul id="options">
		{% for genre in genre_list %}
		<li><a href="{% url 'shop:genre' genre.id %}"> {{ genre.text }} </a></li>
		{% endfor %}
	</ul>
{% endblock %}

{% block optional %}
{% if item.audiosrc %}
    <audio controls autoplay>
        <source src="{{item.audiosrc.url}}" type="audio/mpeg">
    </audio>
{% endif %}
    <div id="price">
        <p><strong>Price:{{item.price}}$</strong>
            <a href="{% url 'shop:cart' item.id %}">
                <button style="margin-left:10px">
                    {% if item.inCart %}
                        Delete from cart
                    {% else %}
                        Add to cart
                    {% endif %}
                </button>
            </a>
        </p>
    </div>

{% endblock %}

{% block section %}
{% if item.videosrc %}
    <video id="final" autoplay controls>
        <source src="{{ item.videosrc.url }}" type="video/mp4">
    </video>
{% elif item.detailImgsrc %}
    <img id="final" src="{{ item.detailImgsrc.url }}" alt="missing image">
{% else %}
   <img id="final" src="{{ item.imgsrc.url }}" alt="missing image">
{% endif %}
{% endblock %}

Entrega/LTAW/PRACTICA4/shop/templates/shop/genre.html
{% extends "shop/base.html" %}

{% load staticfiles %}

{% block aside %}
    <ul id="options">
        {% for item in item_list %}
        <li><a href="{% url 'shop:item' actgenre.id item.id %}">{{ item.text }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

{% block optional %}
{% if actgenre.audiosrc %}
    <audio controls autoplay>
        <source src="{{actgenre.audiosrc.url}}" type="audio/mpeg">
    </audio>
{% endif %}
{% endblock %}

{% block section %}
    <table>
        {% for item in item_list %}
        {% if not forloop.counter|divisibleby:2 %}
        <tr>
        {% endif %}
            <td>
                <div class="item">
                    <a href = "{% url 'shop:item' actgenre.id item.id %}">
                        <img class="itemimg" src="{{item.imgsrc.url}}" alt="missing image">
                    </a>
                    <p> {{ item.text }} </p>
                </div>
            </td>
        {% if forloop.counter|divisibleby:2 %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>
{% endblock %}

Entrega/LTAW/PRACTICA4/shop/templates/shop/index.html
{% extends "shop/base.html" %}

{% load staticfiles %}

{% block aside %}
	<ul id="options">
		{% for genre in genre_list %}
		<li><a href="{% url 'shop:genre' genre.id %}"> {{ genre.text }} </a></li>
		{% endfor %}
	</ul>
{% endblock %}

{% block section %}
	<table>
		{% for genre in genre_list %}
		{% if not forloop.counter|divisibleby:2 %}
		<tr>
		{% endif %}
			<td>
				<div class="item">
					<a href = "{% url 'shop:genre' genre.id %}">
						<img class="itemimg" src="{{genre.imgsrc.url}}" alt="missing image">
					</a>
					<p> {{ genre.text }} </p>
				</div>
			</td>
		{% if forloop.counter|divisibleby:2 %}
		</tr>
		{% endif %}
		{% endfor %}
	</table>
{% endblock %}

Entrega/LTAW/PRACTICA4/shop/templates/shop/search.html
{% extends "shop/base.html" %}

{% load staticfiles %}

{% block aside %}
    <ul id="options">
        {% for item in item_list %}
        <li><a href="{% url 'shop:item' 'search' item.id %}">{{ item.text }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

{% block section %}
    <table>
        {% for item in item_list %}
        {% if not forloop.counter|divisibleby:2 %}
        <tr>
        {% endif %}
            <td>
                <div class="item">
                    <a href = "{% url 'shop:item' 'search' item.id %}">
                        <img class="itemimg" src="{{item.imgsrc.url}}" alt="missing image">
                    </a>
                    <p> {{ item.text }} </p>
                </div>
            </td>
        {% if forloop.counter|divisibleby:2 %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>
{% endblock %}